[general]
debug = true

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501 